// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ats-layout/ATSLayout.tsx": () => import("../components/mockups/ats-layout/ATSLayout.tsx")
};
